# NumPy Array Operation

In [2]:
import numpy as np

## Array Slicing

### 1. Basic Slicing

In [12]:
arr = np.arange(9)
arr=arr+1
print(arr)
print(f"Basic Slicing: {arr[2:7]}")
print(f"With Step: {arr[2:7:2]}")
print(f"Negative Indexing: {arr[-3]}")

[1 2 3 4 5 6 7 8 9]
Basic Slicing: [3 4 5 6 7]
With Step: [3 5 7]
Negative Indexing: 7


### 2. Slicing 2D array

In [21]:
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr_2d)

print(f"The second element of 1st row is: {arr_2d[1,2]}") # numpy syntax, not available in basic python
print(f"The Entire 1st row is: {arr_2d[1]}")
print(f"The Entire 0th column is: {arr_2d[:,0]}") # entire column
print("NB: Indices start from 0")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
The second element of 1st row is: 6
The Entire 1st row is: [4 5 6]
The Entire 0th column is: [1 4 7]
NB: Indices start from 0


### Sorting

In [22]:
unsorted_arr = np.array([1,5,1,7,4,4,3,44,2,6,23,33,34,23])
print(f"Sorted array: {np.sort(unsorted_arr)}")

Sorted array: [ 1  1  2  3  4  4  5  6  7 23 23 33 34 44]


### Sorting 2D array

In [38]:
arr_2d_unsorted = np.array([
    [3,1],
    [1,2],
    [2,3]
])
print(arr_2d_unsorted)

print(f"Sorting based on column:\n {np.sort(arr_2d_unsorted, 0)}")
print(f"Sorting based on row:\n {np.sort(arr_2d_unsorted, 1)}")
print(f"The original 2D array is:\n {arr_2d_unsorted}")
print(f"Sorting col 0:\n {np.sort(arr_2d_unsorted[:, 0], 0)}")

[[3 1]
 [1 2]
 [2 3]]
Sorting based on column:
 [[1 1]
 [2 2]
 [3 3]]
Sorting based on row:
 [[1 3]
 [1 2]
 [2 3]]
The original 2D array is:
 [[3 1]
 [1 2]
 [2 3]]
Sorting col 0:
 [1 2 3]


### Filtering Array

In [ ]:
numbers = np.arange(11)
print(numbers)
print(f"Even numbers are:\n {numbers[numbers%2 == 0]}")

[ 0  1  2  3  4  5  6  7  8  9 10]
Even numbers are:
 [ 0  2  4  6  8 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


### Filtering with Mask

In [ ]:
mask = numbers % 5 == 0
print(f"Masked filtering: {numbers[mask]}")

Masked filtering: [ 0  5 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


### Fancy Indexing and np.where()

In [73]:
numbers+=1
print(numbers)
idx = [0,2,4,5, 1]
print(numbers[idx])

np_where = np.where((numbers >= 25)  & (numbers < 30))
print(f"Using where clause: {numbers[np_where]}")

[16 17 18 19 20 21 22 23 24 25 26]
[16 18 20 21 17]
Using where clause: [25 26]
