# NumPy Array Operation

In [2]:
import numpy as np

## Array Slicing

### 1. Basic Slicing

In [12]:
arr = np.arange(9)
arr=arr+1
print(arr)
print(f"Basic Slicing: {arr[2:7]}")
print(f"With Step: {arr[2:7:2]}")
print(f"Negative Indexing: {arr[-3]}")

[1 2 3 4 5 6 7 8 9]
Basic Slicing: [3 4 5 6 7]
With Step: [3 5 7]
Negative Indexing: 7


### 2. Slicing 2D array

In [21]:
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr_2d)

print(f"The second element of 1st row is: {arr_2d[1,2]}") # numpy syntax, not available in basic python
print(f"The Entire 1st row is: {arr_2d[1]}")
print(f"The Entire 0th column is: {arr_2d[:,0]}") # entire column
print("NB: Indices start from 0")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
The second element of 1st row is: 6
The Entire 1st row is: [4 5 6]
The Entire 0th column is: [1 4 7]
NB: Indices start from 0


### Sorting

In [22]:
unsorted_arr = np.array([1,5,1,7,4,4,3,44,2,6,23,33,34,23])
print(f"Sorted array: {np.sort(unsorted_arr)}")

Sorted array: [ 1  1  2  3  4  4  5  6  7 23 23 33 34 44]
