# Advance Operations with Business Examples

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],
    [2, 120000, 140000, 160000, 190000],
    [3, 200000, 230000, 260000, 300000],
    [4, 180000, 210000, 240000, 270000],
    [5, 160000, 185000, 205000, 230000]
])

print("==================== Zomate Sales Report ====================")
print(sales_data)

==================== Zomate Sales Report ====================
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
