# Advance Operations with Business Examples

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],
    [2, 120000, 140000, 160000, 190000],
    [3, 200000, 230000, 260000, 300000],
    [4, 180000, 210000, 240000, 270000],
    [5, 160000, 185000, 205000, 230000]
])

print("==================== Zomate Sales Report ====================")
print(sales_data)
sales_data_shape = sales_data.shape
print(f"Shape of the sales data is: {sales_data_shape}")

==================== Zomate Sales Report ====================
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
Shape of the sales data is: (5, 5)


### Q1. Display the data of first three restaurants

In [5]:
res1 = sales_data[0:3]
res2 = sales_data[:, 1:]
print(res1)
print()
print(res2)

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

[[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


### Q2. Find the total sales per year for each restaurant.

In [8]:
total_sales = np.sum(sales_data[:, 1:], axis=1)
print(total_sales)
res = np.sum(total_sales)
print(res)

[800000 610000 990000 900000 780000]
4080000


# Q3. (i). Find the Minimum sales per restaurant.
# (ii). Find maximum sales per year.

In [10]:
min_sales = np.min(sales_data[:,1:], 1)
print(min_sales)
max_sales_per_year = np.max(sales_data[:,1:], 0)
print(max_sales_per_year)

[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]
