In [ ]:
## Learning Numpy for the first time.
## Numpy Array Basics
## Day 1

In [5]:
import numpy as np

### Creating Array from List

In [4]:
arr_1D = np.array([1,2,3,4,5])
arr_2D = np.array([[1,2,3], [4,5,6]])
print(f"1D array is: {arr_1D}")
print(f"2D array is: {arr_2D}")

1D array is: [1 2 3 4 5]
2D array is: [[1 2 3]
 [4 5 6]]


### List vs Numpy Array

In [5]:
py_list = [1,2,3]
np_arr = np.array([1,2,3])
print(f"List multiplication is: {py_list*2}")
print(f"Array multiplication is: {np_arr*2}")

List multiplication is: [1, 2, 3, 1, 2, 3]
Array multiplication is: [2 4 6]


In [6]:
np_range = np.arange(100) # stop position
print(np_range)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [8]:
np_range = np.arange(1,100)  # start, stop positions
print(np_range)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [16]:
np_range = np.arange(2,1000, 5)  # start, stop, step positions
print(np_range)

[  2   7  12  17  22  27  32  37  42  47  52  57  62  67  72  77  82  87
  92  97 102 107 112 117 122 127 132 137 142 147 152 157 162 167 172 177
 182 187 192 197 202 207 212 217 222 227 232 237 242 247 252 257 262 267
 272 277 282 287 292 297 302 307 312 317 322 327 332 337 342 347 352 357
 362 367 372 377 382 387 392 397 402 407 412 417 422 427 432 437 442 447
 452 457 462 467 472 477 482 487 492 497 502 507 512 517 522 527 532 537
 542 547 552 557 562 567 572 577 582 587 592 597 602 607 612 617 622 627
 632 637 642 647 652 657 662 667 672 677 682 687 692 697 702 707 712 717
 722 727 732 737 742 747 752 757 762 767 772 777 782 787 792 797 802 807
 812 817 822 827 832 837 842 847 852 857 862 867 872 877 882 887 892 897
 902 907 912 917 922 927 932 937 942 947 952 957 962 967 972 977 982 987
 992 997]


In [18]:
np_range = np.arange(1, 1000, 2)  # start, stop, step positions
print(np_range)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
 433 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467
 469 471 473 475 477 479 481 483 485 487 489 491 49

In [32]:
np_zeros = np.zeros((3,3))
print(np_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
np_zeros = np.zeros((1,10))
print(np_zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [38]:
np_ones = np.ones((3,3))
print(np_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [35]:
np_1_single = np.ones(6)
np_1_zeros = np.zeros(6)
print(np_1_single)
print(np_1_zeros)

[1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0.]


In [36]:
full_multi = np.full((3,3), 9)
full_single = np.full(5,9)
print(full_multi)
print(full_single)

[[9 9 9]
 [9 9 9]
 [9 9 9]]
[9 9 9 9 9]


In [41]:
sum_arr = np_zeros + np_ones + full_multi+6
print(sum_arr)

[[16. 16. 16.]
 [16. 16. 16.]
 [16. 16. 16.]]


In [42]:
random_arr = np.random.random(4)
print(random_arr)

[0.79207284 0.41374614 0.80946285 0.13799066]


In [47]:
random_arr = np.random.random((3,3))
print(random_arr)

[[0.74204607 0.67389339 0.9233362 ]
 [0.27708578 0.92951692 0.92066609]
 [0.99930688 0.88040647 0.55256544]]


### Vector, Matrix and Tensor

In [8]:
vector1 = np.array([1,2,3])
print(f"Vector is: {vector1}")
array_matrix = np.array([[1,2,3], [4,5,6]])
print(f"Matrix is: {array_matrix}")

Vector is: [1 2 3]
Matrix is: [[1 2 3]
 [4 5 6]]


In [12]:
t1 = np.array([[[1, 2], [3, 4]],
               [[5,6], [7,8]]])

print(t1)

print(f"{t1.shape}, {t1.ndim}, {t1.size}, {t1.dtype}")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2), 3, 8, int64


### Array Properties

In [24]:
arr_properties = np.array([[1,2,3], [4,5,6]])
arr_properties_2 = np.array([1,2,3])
print(f"Shape of the array is: {arr_properties.shape}")
print(f"Dimension of the array is: {arr_properties.ndim}")
print(f"Size of the array is: {arr_properties.size}")
print(f"Datatype of the array is: {arr_properties.dtype}")

print(f"Shape of the array 2 is: {arr_properties_2.shape}")
print(f"Dimension of the array 2 is: {arr_properties_2.ndim}")

Shape of the array is: (2, 3)
Dimension of the array is: 2
Size of the array is: 6
Datatype of the array is: int64
Shape of the array 2 is: (3,)
Dimension of the array 2 is: 1


### Array Reshaping

In [21]:
og_arr = np.arange(12)
print(f"The Orifinal Array is:\n{og_arr}")
rshape_arr = og_arr.reshape((3,4))
print(rshape_arr)

The Orifinal Array is:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Array Flatening

In [25]:
flatten_arr = rshape_arr.flatten()
print(flatten_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
